project_id = "vjrzedpujsdcyeoqbzfg"

[functions.consulta-placa]
verify_jwt = false

[functions.submit-to-crm]
verify_jwt = false

[functions.update-inspection]
verify_jwt = false

[functions.get-inspection-link]
verify_jwt = false

[functions.get-crm-plans]
verify_jwt = false

[functions.consulta-placa-crm]
verify_jwt = false